<?xml version="1.0" encoding="utf-8"?><Database Name="SCCMLogs" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WACSQLTEST01;Initial Catalog=SCCMLogs;Integrated Security=True" SettingsObjectName="ParseSCCMLogs.Properties.Settings" SettingsPropertyName="SCCMLogsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hostname" Member="Hostnames">
    <Type Name="Hostname">
      <Column Name="HostnameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hostname" Member="Hostname1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="LastDateEntered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Hostname_LogText" Member="LogTexts" ThisKey="HostnameID" OtherKey="HostnameID" Type="LogText" />
    </Type>
  </Table>
  <Table Name="dbo.LogText" Member="LogTexts">
    <Type Name="LogText">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HostnameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Component" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="dateTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Thread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="Hostname_LogText" Member="Hostname" ThisKey="HostnameID" OtherKey="HostnameID" Type="Hostname" IsForeignKey="true" />
    </Type>
  </Table>
</Database>